baseURL = "https://example.com"

disableKinds = ["taxonomy", "term", "section"]

[module]
    [[module.imports]]
        path = "github.com/bep/gallerydeluxe_starter"

[imaging]
    resampleFilter = "CatmullRom"
    quality        = 71
    anchor         = "smart"
    [imaging.exif]
        disableDate    = false
        disableLatLong = true
        includeFields  = 'Artist|LensModel|FNumber|ExposureTime'
